.github/workflows/tests.yml, README.md
=> docs: update readme

README.md, demo/index.html, package.json, src/csrf.ts, src/method.ts, src/mrujs.ts, src/utils.ts, src/utils/observer.ts
still needs testing, added as part of 0.1.0-beta.1 release.
=> feat: add `data-method` support

.github/workflows/tests.yml, README.md, lib/mrujs_rails/assertions.rb, lib/mrujs_rails/controller.rb, lib/mrujs_rails/engine.rb, lib/mrujs_rails/redirection.rb, lib/tasks/mrujs_rails_tasks.rake, src/ajax.ts, src/confirm.ts, src/index.ts, src/mrujs.ts
Add turbolinks adapter
closes #15
=> feat: create turbolinks adapter

src/ajax.ts, src/confirm.ts, src/utils/events.ts
Ready 
Adds abort controllers for abortable fetches.
* closes #5
=> add abort controller

src/csrf.ts, src/formSubmission.ts, src/formSubmitDispatcher.ts, src/http/fetchRequest.ts, src/http/fetchResponse.ts, src/navigationAdapter.ts, src/utils/url.ts
Ready
* fixes: navigation adapter was broken
* fixes: issues with form bodies
=> fix: how navigation and body are appended

src/method.ts, src/navigationAdapter.ts
* Ready
Navigation now happens via fetch on `<a data-remote="true">remote</a>`
=> feat: method navigation with fetch

package.json, src/linkSubmission.ts, src/method.ts, src/navigationAdapter.ts, src/utils/form.ts, src/utils/headers.ts, test/rails/dummy/app/controllers/posts_controller.rb, test/rails/dummy/app/controllers/remote_links_controller.rb, test/rails/dummy/app/views/remote_links/index.html.erb, test/rails/dummy/config/routes.rb, test/rails/dummy/test/system/remote_links_test.rb, test/rails/dummy/yarn.lock
Ready
- Fixes issues with `data-remote` + `data-method` elements that werent submitting properly.
=> fix: data-remote link submissions

package.json, src/http/fetchResponse.ts
=> Feat: Add checks for json responses.

package.json, src/addedNodesObserver.ts, src/clickHandler.ts, src/confirm.ts, src/csrf.ts, src/method.ts, src/mrujs.ts, src/toggler.ts, src/utils/dom.ts, test/rails/dummy/app/javascript/packs/application.js, test/rails/dummy/app/views/remote_links/index.html.erb, test/rails/dummy/test/system/remote_links_test.rb, test/rails/dummy/yarn.lock
Ready!!
Closes #42 
MutationObservers for everything!! This removes any need for restarts. The mutation observers will monitor changes and attach events as needed!
=> It lives! Mutation Observers for all!

Gemfile, Gemfile.lock, README.md, package.json, src/clickHandler.ts, src/confirm.ts, src/formSubmitDispatcher.ts, src/http/fetchRequest.ts, src/index.ts, src/method.ts, src/mrujs.ts, src/toggler.ts, src/types.ts, src/utils/dom.ts, test/js/index.test.ts, test/rails/dummy/yarn.lock, yarn.lock
Ready
Allows for custom querySelectors to be set.
=> feat: custom query selectors

package.json, src/confirm.ts, src/mrujs.ts, test/rails/dummy/app/controllers/posts_controller.rb, test/rails/dummy/app/javascript/packs/application.js, test/rails/dummy/test/system/remote_forms_test.rb, test/rails/dummy/yarn.lock
Ready
Fixes how the confirm dialog works and fixes event ordering.
=> Tests: work on data disable testing

package.json, src/addedNodesObserver.ts, src/mrujs.ts, src/utils/dom.ts
Ready
- Fixes the addedNodesObserver to observe a subset of attributes.
=> fix: addedNodesObserver properly observes attributes now

CHANGELOG.md, README.md, package.json, src/cable_ready.d.ts, src/http/fetchResponse.ts, src/index.ts, src/plugins/cableCar.ts, src/types.ts, test/js/plugin.test.ts, test/js/plugins/cableCar.test.html, test/js/plugins/cableCar.test.ts, tsconfig.json, yarn.lock
Ready
Co-Authored-By: @leastbad
=> feat: add CableCar plugin

docs/snowpack.config.js
* (WIP, Ready, Needs Review)
* closes / fixes #
=> add hot reloading

src/utils/dom.ts
Ready
closes #73 
Quotes...good times.
=> fix: querySelectors for Turbo

docs/frontend/styles/defaults.css, docs/snowpack.config.js, docs/src/_documentation/how_tos/integrate-cablecar.md, docs/src/_documentation/how_tos/prefetching.md, docs/src/_documentation/references/ajax_lifecycle.md, package.json, src/elementEnabler.ts, src/http/fetchRequest.ts, src/mrujs.ts, src/navigationAdapter.ts, src/types.ts, src/utils/url.ts, test/rails/dummy/package.json, test/rails/dummy/test/system/navigation_adapter_tests.rb, test/rails/dummy/test/system/turbo_navigation_adapter_test.rb, test/rails/dummy/test/system/turbo_remote_forms_test.rb, test/rails/dummy/test/system/turbo_remote_links_test.rb, test/rails/dummy/test/system/turbolinks_navigation_adapter_test.rb, test/rails/dummy/test/system/turbolinks_remote_forms_test.rb, test/rails/dummy/test/system/turbolinks_remote_links_test.rb, test/rails/dummy/test/turbo_test_case.rb, test/rails/dummy/test/turbolinks_test_case.rb, test/rails/dummy/yarn.lock
Ready
* closes #70 
- Fixes a regression in element enabling
- Exposes the following APIs:
```js
window.mrujs.navigationAdapter.snapshotCache // => returns the Turbo(links) cache.
window.mrujs.navigationAdapter.prefetch({ url: "/hi", html: "<div>Hi</div>" })
window.mrujs.navigationAdapter.cacheContains("/hi") // => true
```
=> Feat: add cache operations

Gemfile.lock, docs/Gemfile.lock, docs/frontend/styles/defaults.css, docs/package.json, docs/src/_components/alert.rb, docs/src/_documentation/how_tos/prefetching.md, docs/yarn.lock, package.json
=> fix documentation issues

docs/src/_data/site_metadata.yml, docs/src/_partials/_footer.erb, docs/src/_partials/_top_nav.erb
Ready
\-
also fix capitalization of "GitHub" 😉
=> fix `doc_location` to prevent 404 on the "Edit this page on GitHub" link

docs/plugins/builders/helpers.rb, docs/src/_layouts/home.erb, docs/src/_partials/_logo.erb, docs/src/_partials/_side_nav_mobile.erb, docs/src/_partials/_top_nav.erb, docs/src/_partials/_version_number.erb
=> docs: add version numbering to docs

src/navigationAdapter.ts, src/utils/url.ts, test/rails/dummy/app/controllers/posts_controller.rb, test/rails/dummy/app/views/posts/_form.html.erb, test/rails/dummy/package.json, test/rails/dummy/test/system/remote_form_tests.rb, test/rails/dummy/yarn.lock
fix: allow cancelling navAdapter
Ready
=> fix: allow for cancelling nav adapter

docs/src/_documentation/references/ajax_lifecycle.md, package.json, src/formSubmitDispatcher.ts
=> Feat: add status to event.detail

package.json, src/index.ts, src/mrujs.ts, yarn.lock
Ready
Adds microbundle so it can be served from unpkg.
=> Chore: add microbundle

docs/frontend/styles/components.css, docs/src/_documentation/references/remote_forms_and_links.md, docs/src/_documentation/tutorials/practical-guide-to-mrujs.md, docs/src/_partials/_top_nav.erb, docs/yarn.lock, src/elementDisabler.ts, src/elementEnabler.ts, src/mrujs.ts, src/navigationAdapter.ts, src/utils/dom.ts
Ready
- Allows opting out of the navigationAdapter
- Removes `data-remote="true"` being required on buttons
- Adds docs for new users.
=> Docs: add new user area

docs/src/_documentation/how_tos/programmatic-fetching-with-events.md, src/formSubmission.ts, src/http/fetchRequest.ts, src/mrujs.ts, src/types.ts, test/js/ajax/ajaxFetch.test.ts
Ready
closes #40
Adds `dispatchEvents` to options.
=> fix: GET requests now properly submit URLSearchParams

docs/src/_documentation/references/async_confirms.md, src/addedNodesObserver.ts, src/confirm.ts, src/customElements/mrujs-confirm.ts, src/formSubmitDispatcher.ts, src/mrujs.ts, src/utils/dom.ts, test/rails/dummy/app/views/posts/index.html.erb
Ready
Starts the process of async confirm dialogs.
=> Feat: add async confirm dialogs

src/plugins/cableCar.ts, test/js/plugins/cableCar.test.ts
Ready
Extends #100 
Fixes render_to_string issues when rendering from a Rails controller.
Co-Authored-By: @existentialmutt
=> fix: CableCar mime types more permissive.

package.json, rollup.config.js, tsconfig.json, yarn.lock
Ready
- Adds a proper rollup config
=> minor tweaks

docs/src/_documentation/how_tos/make-every-form-remote-in-rails.md, docs/src/_documentation/references/remote_forms_and_links.md, docs/src/_documentation/tutorials/getting-started.md, src/addedNodesObserver.ts, src/confirm.ts, src/method.ts, src/mrujs.ts, src/navigationAdapter.ts, src/remoteWatcher.ts, src/types.ts, src/utils/dom.ts, test/js/remoteWatcher/remoteWatcher.test.html, test/js/remoteWatcher/remoteWatcher.test.ts, test/rails/dummy/app/views/posts/_form.html.erb, test/rails/dummy/app/views/posts/index.html.erb, test/rails/dummy/app/views/remote_links/index.html.erb, test/rails/dummy/package.json, test/rails/dummy/yarn.lock
WIP
- closes #107
- closes #105 
- Auto attaches `data-turbo` for remote forms + links.
- Adds documentation about auto remote forms.
=> Feat: auto attach data-turbo="false"

docs/src/_documentation/references/known_issues.md
Ready
None. Mentioned in Discord.
The previous text gave the impression that there were bugs with the Turbo integration which hadn't been fixed yet. They're all fixed :ok_hand:
=> Update Known Issues docs

docs/src/_documentation/how_tos/use-js-erb.md, docs/src/_documentation/references/comparison-to-ujs.md, plugins/src/cableCar.ts, plugins/src/index.ts, plugins/src/jsErb.ts, src/http/fetchResponse.ts, src/navigationAdapter.ts, src/utils/headers.ts, test/rails/dummy/app/controllers/posts_controller.rb, test/rails/dummy/app/javascript/packs/application.js, test/rails/dummy/app/views/posts/create.js.erb, test/rails/dummy/config/initializers/content_security_policy.rb
Ready
Adds .js.erb via a plugin.
```js
import mrujs from "mrujs"
import { JsErb } from "mrujs/plugins"
mrujs.start({
plugins: [
JsErb()
]
})
```
=> feat: support js.erb

src/formSubmission.ts, src/submitFinder.ts
* (WIP, Ready, Needs Review)
* closes / fixes #
=> fix: getHeaders not receiving element

src/http/fetchResponse.ts
Ready
- Fixes the issue with double response bodies @leastbad
=> fix: use response.clone()

src/utils/misc.ts
Ready
Bye-bye invalidAuthenticityToken garbage
=> fix: invalid authenticity token crap

src/elementDisabler.ts, src/elementEnabler.ts, src/formSubmitDispatcher.ts, src/mrujs.ts, src/types.ts, src/utils/events.ts
Ready
https://github.com/rails/rails/blob/ae1c7a440a52e2e5494a45bb5befec04a500e325/actionview/app/assets/javascripts/rails-ujs/start.coffee#L62-L63
=> fix: element disabling aligned with rails-ujs

.github/workflows/tests.yml, Gemfile, Gemfile.lock
=> remove 2.6 test, 2.7 is minimum

src/index.ts, src/polyfills/submit-event.ts
Ready
* closes #131 
Co-Authored-By: @terracatta
=> fix: submit-event-polyfill

src/elementDisabler.ts, src/elementEnabler.ts
Ready
* closes #104 
Co-Authored-By: @virolea
=> feat: disable <select> elements on change

src/mrujs.ts, test/js/remoteWatcher/remoteWatcher.test.ts
=> fix: use animation frames when nodes are added

docs/src/_documentation/tutorials/practical-guide-to-mrujs.md
I noticed it was giving the same code example twice, but the second one isn't right
* Needs Review
=> Update code example in practical guide

Rakefile, src/clickHandler.ts, src/confirm.ts, src/csrf.ts, src/disabledElementChecker.ts, src/elementDisabler.ts, src/elementEnabler.ts, src/mrujs.ts, src/remoteWatcher.ts, src/types.ts
Ready
- dont recall functions for queries, cache the call.
- use setTimeout instead of rAF
=> fix: minor perf improvements

docs/src/_documentation/how_tos/using-shoelace-with-mrujs.md, plugins/src/shoelace.ts
Ready
- Adds a shoelace plugin for automatically submitting Shoelace forms over AJAX.
- Adds notes about ViewHelpers by @yuki24
=> feat: add shoelace-plugin

src/methodSubmission.ts
Ready
Fixes typechecking for strings.
=> fix: conditional operator on formdata

plugins/src/jsErb.ts, src/polyfills/submit-event.ts
Ready
Found these while debugging .js.erb
=> fix: jsErb headers and submit-event polyfill

docs/plugins/builders/helpers.rb, docs/src/_documentation/how_tos/10-make-every-form-remote-in-rails.md, docs/src/_documentation/how_tos/20-programmatic-fetching-with-events.md, docs/src/_documentation/how_tos/30-use-js-erb.md, docs/src/_documentation/how_tos/40-prefetching.md, docs/src/_documentation/how_tos/50-integrate-cablecar.md, docs/src/_documentation/how_tos/60-integrate-turbo.md, docs/src/_documentation/how_tos/70-using-shoelace-with-mrujs.md, docs/src/_documentation/references/01-comparison-to-ujs.md, docs/src/_documentation/references/02-remote-forms-and-links.md, docs/src/_documentation/references/03-ajax-lifecycle.md, docs/src/_documentation/references/04-mime-types.md, docs/src/_documentation/references/05-fetch.md, docs/src/_documentation/references/06-query-selectors.md, docs/src/_documentation/references/07-integrations.md, docs/src/_documentation/references/08-plugins.md, docs/src/_documentation/references/09-known-issues.md, docs/src/_documentation/references/10-async-confirms.md, docs/src/_documentation/references/11-understanding-method-masking.md, docs/src/_documentation/tutorials/01-getting-started.md, docs/src/_documentation/tutorials/02-practical-guide-to-mrujs.md
Ready
@jaredcwhite Bridgetown is <3
=> Logical doc ordering by filename.

docs/src/_documentation/references/09-known-issues.md
=> docs: add note about rails-ujs

src/polyfills/submit-event.ts
* Ready
* See also https://github.com/hotwired/turbo/issues/523
=> Don't declare global types in polyfills/submit-event.ts

src/confirm.ts
=> fix: confirm:complete now fires appropriately

docs/src/_documentation/how_tos/09-use-an-alternate-error-renderer.md, src/index.ts, src/navigationAdapter.ts, types.ts
Ready
Fixes issues with Shoelace + morphdom.
https://twitter.com/RogersKonnor/status/1502778310174068738
=> feat: allow alternate rendering techniques

docs/src/_documentation/how_tos/10-set-a-morph-root.md, src/navigationAdapter.ts
=> docs: add morph root to docs

.github/workflows/tests.yml, package.json, pnpm-lock.yaml
* (WIP, Ready, Needs Review)
* closes / fixes #
=> fix ci test suitE

README.md, pnpm-lock.yaml, src/method.ts, src/utils/misc.ts
Ready
Fixes #216 
No tests...because YOLO, but im pretty positive this should work.
=> fix: dont try to submit links that are alt / ctrl clicked
