KonnorRogers/mrujs

src/http/fetchResponse.ts
src/index.ts
test/js/ajax/ajax.test.html
test/js/ajax/ajaxFetch.test.ts

Ready
- Allows for responseBodies to be consumed multiple times.
```js
const response = new FetchResponse(await window.fetch())
await response.responseHtml
await response.responseHtml // => no error.
```

feat: allow response bodies to be consumed multiple times.

---

README.md
package.json
src/method.ts
src/navigationAdapter.ts
test/js/ajax/ajax.test.html
test/js/ajax/ajaxEvents.test.ts
test/rails/dummy/app/views/remote_links/index.html.erb
test/rails/dummy/test/system/remote_links_test.rb

* Ready
`data-remote data-method` links in UJS went through the event pipeline. This will do the same starting with `ajax:before`.
closes #38

Feat: send method through events

---

README.md
src/formSubmitDispatcher.ts
src/http/fetchRequest.ts
src/mrujs.ts
src/utils/events.ts
test/js/ajax/ajaxEvents.test.ts

Ready
When UJS events stop firing, it initiates an `ajax:stopped` event. This PR mimics that same behavior.

feat: add ajax:stopped event

---

README.md
package.json
src/http/fetchResponse.ts
src/mrujs.ts
src/types.ts
src/utils/headers.ts
test/js/index.test.ts

Ready
Allows registering of custom content types for shortcutting `data-type`.
See README.md for more info on custom mime types.

Feat: content type shortcuts

---

README.md

This was tripping me up but I got it to work by assigning headers within a `headers: {}` entry.  This is consistent with the standard fetch API.
* Ready

update documentation for fetch headers

---

package.json
src/method.ts
test/js/ajax/ajax.test.html
test/js/ajax/ajaxEvents.test.ts

Ready
Handles logic around remote links with nested elements. Previously it was calling `event.target`. This changes it to `event.currentTarget` which will properly identify the anchor submitting the request.

Fix: remote link submissions

---

package.json
src/plugins/cableCar.ts
test/js/plugins/cableCar.test.ts
test/js/plugins/cableCarMimeType.test.html
test/js/plugins/cableCarMimeType.test.ts
yarn.lock

* Needs Review
(none)
I suspect json will continue being the default, but I've been using `text/vnd.cablecar.json` as the mime type for my mrujs/cablecar projects and I really like the possibilities it opens up inside Rails controllers.  This PR allows the user to specify a custom mime type when initializing the cablecar plugin so you can do something like:
```javascript
import CableReady from 'cable_ready'
import mrujs, { CableCar } from "mrujs"
mrujs.registerMimeTypes(
[
{shortcut: "cablecar", header: "text/vnd.cablecar.json"}
]
)
mrujs.start({plugins: [new CableCar(CableReady, {mimeType: "cablecar"})]});
```

feat(cablecar): allow custom default mime types

---

src/clickHandler.ts
src/confirm.ts
src/method.ts
src/mrujs.ts
src/toggler.ts

* Needs Review
(that thing I mentioned on discord)
I noticed that remote link behavior wasn't being correctly attaching if you added `data-remote` to an existing link.
Digging into things, it looks like `mrujs.addedNodesCallback` was calling the various observer callbacks with `mutation.addedNodes` which is blank when the mutation is an attribute change.
I've updated the behavior in `mrujs.addedNodesCallback` to use `mutation.target` if the mutation is an attribute change.
This also required updating the method signatures of the observerCallback functions from `NodeList` to `Node[]`,  because the browser doesn't let you create your own NodeLists.
This change is important to get the cablecar plugin fully working.  That plugin adds data-remote attributes to links but this PR is necessary to …

fix: event listeners now attach properly when attributes change

---

src/http/fetchResponse.ts
src/navigationAdapter.ts
src/types.ts
test/rails/dummy/app/controllers/static_controller.rb
test/rails/dummy/app/views/remote_links/index.html.erb
test/rails/dummy/config/routes.rb
test/rails/dummy/test/system/remote_link_tests.rb

Ready
This was an issue raised by @Erlingur where ajax get links didnt have the same behavior as rails-ujs navigation.
Before I merge + release, anyone have an issue with this?
IF you dont want your page to navigate, your links should look like this:
```html
<a href="/blah" data-method="get" data-ujs-navigate="false">Dont navigate!</a>
```

fix: uses UJS based navigation for AJAX GET links.

---

rollup.config.js
src/polyfills/submit-event.ts

Ready
* fixes #113
Will submit a PR to Turbo as well so ordering of dependencies wont matter.
As of right now, you must import Turbo before mrujs for unsupported browsers.

fix: submitter already defined on Event prototype

---

docs/src/_documentation/how_tos/integrate-cablecar.md
plugins/src/asyncConfirm/index.ts
plugins/src/cableCar.ts
plugins/src/index.ts
plugins/src/jsErb.ts
src/index.ts
src/navigationAdapter.ts
src/types.ts
test/js/ajax/ajaxEvents.test.ts
test/js/plugins/cableCar.test.ts
test/js/plugins/cableCarMimeType.test.ts
tsconfig-plugins.json

Ready
Refactors how cablecar attaches headers.
End users now only need to specify `data-remote` or `data-method` and all AJAX requests will default to using the CableCar header. If a user wants to opt-out on a per element basis, they should pass in a `data-type="<type>"`

Fix: CableCar refactor

---

docs/src/_documentation/how_tos/integrate-turbo-streams.md
docs/src/_documentation/references/ajax_lifecycle.md
plugins/src/cableCar.ts
plugins/src/index.ts
plugins/src/mrujsTurbo.ts
src/navigationAdapter.ts
src/utils/events.ts

Ready
* closes #122 
Some additional things to make this work because a turbo stream passes HTML validation on fetchResponses so I had to be clever and add a new event prior to the navigationAdapter to allow for plugins to hook in prior to it.

Feat: add turbo stream integration

---

docs/src/_documentation/how_tos/integrate-cablecar.md

* Ready (CableReady… 😉)
I got this working in Bridgetown (w00t!), but it took me a bit of time to figure out the steps and I realized the MIME type in the docs didn't match the latest mrujs code. Here are some suggested improvements to the docs page.

Update CableCar installation instructions

---

src/elementDisabler.ts
src/elementEnabler.ts

Ready
Fixes #141 
Any time a turbo-submit is sent, the form will be disabled, and then re-enabled when the submit finishes.

fix: disable form submits from Turbo

---

src/elementDisabler.ts
src/method.ts
src/utils/dom.ts
test/rails/dummy/app/javascript/packs/application.js
test/rails/dummy/app/views/posts/_form.html.erb

Ready
Fixes a bug where button based submitters would not work.
Also changes logic for buttons querySelectors, and links no longer stop everything (@davidcolby)

fix: button submitters now work

---

src/navigationAdapter.ts

Needs review
Add in a new data attribute called "ujs-selector' which is a string that is used to query the page to find an element . If the element is found it will be subjected to morphdom, if it's not found, default to document.body (as before). This is very handy for updating the DOM with partials.
I'm wondering whether it would be worth addding a couple of additional data selector attributes for `success` vs `failed` response as opposed to a universal selector data attribute. What do you think?

feat: Add `data-ujs-morph-root` for morphdom rendering

---

docs/src/_documentation/how_tos/05-integrate-cablecar.md
plugins/src/cableCar.ts
test/js/plugins/cableCar.ts

Since https://github.com/stimulusreflex/cable_ready/pull/260, `cable_ready` changed its Content-Type to `text/vnd.cable-ready.json`. This commit updates the default one used by mrujs to be compatible with `cable_ready`.
Context: https://github.com/stimulusreflex/cable_ready/issues/272
* Ready, Needs Review

fix: update default `Content-Type` to reflect the one used by `cable_ready`: `text/vnd.cable-ready.json`

---

src/navigationAdapter.ts

* Needs Review
-
I ran into a case where I was trying to apply some logic after page transitions where the user's session might have changed, and I hit this issue where 95% of the time I could hook into `"turbo:load"` events but 5% of the time (and depending on which page the user was on, and what the controller response was doing) the session change resulted in `mrujs` doing a page morph buuuuut there's no events that gets fired when that happens so there's nothing to listen for. So an event here would be really helpful.
I wasn't sure about the naming; it somewhat breaks from the convention of `"ajax:<eventname>"`, but it feels like this event announcing an mrujs/morphdom update isn't related to ajax? As always, _naming things is hard_ :man_shrugging:

Emit "ujs:afterMorph" event after applying a page morph

---

src/navigationAdapter.ts
test/rails/dummy/app/controllers/morphs_controller.rb
test/rails/dummy/app/views/layouts/application.html.erb
test/rails/dummy/app/views/morphs/index.html.erb
test/rails/dummy/config/routes.rb
test/rails/dummy/test/system/morph_test.rb

* Needs Review
-
There's currently a weird bug in the way that `mrujs` mophs the html response on to the current page, but it's a bit silent because it tends to not actually break anything too important. The response contains a full HTML document, but when it's applied to the current page via morphdom, content inside the response's `<head>` element gets injected into the `<body>` in the DOM in a weird way. The DOM looks like this after `morphHTML` is called:
So the elements that were meant to be written to the head get written into the body and there's duplicates. Most of the time this doesn't actually break anything and the problem gets cleaned up after the user navigates away from the page... except if you happen to be using meta tags in weird ways to pass bits of data that are then …

BREAKING_CHANGE: issue with `<head>` content not being morphed correctly

---

docs/src/_partials/_head.erb
package.json

The website currently linked on npm doesn't appear to be associated with this project.
Social image previews also don't work as they point to the same website.

Update website links
